name = "MiscUtil"
uuid = "e472fcb8-ab9f-4ff8-82d2-c5cadce53af3"
authors = ["ngiann <ngiann@gmail.com> and contributors"]
version = "0.1.12"

[deps]
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
Crayons = "4"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
